// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIRRjxjPqKkDju2_bY2N2GJv02NlFYTTQ',
    appId: '1:139701247462:web:da1e09f7db088bca50ca27',
    messagingSenderId: '139701247462',
    projectId: 'login-app-6f06f',
    authDomain: 'login-app-6f06f.firebaseapp.com',
    storageBucket: 'login-app-6f06f.appspot.com',
    measurementId: 'G-BYG8PT2QRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB50iXHFDFZZ9ExmUOCHO5fE10ACQ4XmU',
    appId: '1:139701247462:android:8ce9e0e438fcb5fb50ca27',
    messagingSenderId: '139701247462',
    projectId: 'login-app-6f06f',
    storageBucket: 'login-app-6f06f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiu6a0RnpnQxtQDUQUoYQp5gkQGFkK83s',
    appId: '1:139701247462:ios:2a13470b52d2bacf50ca27',
    messagingSenderId: '139701247462',
    projectId: 'login-app-6f06f',
    storageBucket: 'login-app-6f06f.appspot.com',
    iosBundleId: 'com.andyg.loginAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiu6a0RnpnQxtQDUQUoYQp5gkQGFkK83s',
    appId: '1:139701247462:ios:03dbfa74cd32105d50ca27',
    messagingSenderId: '139701247462',
    projectId: 'login-app-6f06f',
    storageBucket: 'login-app-6f06f.appspot.com',
    iosBundleId: 'com.andyg.loginAppFlutter.RunnerTests',
  );
}
